version: '3'

services: 
  koa:
    build: .
    container_name: koa
    env_file:
      - ./config/.env
    ports:
      - "8000:8000"
    restart: always
    volumes: 
      - ./data/log:/shintech/log